[package]
name = "rust_vault"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
log = "0.4.22"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.135"
thiserror = "2.0.11"
tokio = "1.43.0"
